name: Bug report
description: Create a report to help us improve this project
labels: [ "bug", "triage" ]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to submit a bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Platform / version
      description: What platform, browser, Node.js / npm version, etc. are you seeing the problem on?
      value: |
        - OS + version: (e.g. iOS 17.2)
        - Node version: (e.g. Node.js 20.5)
        - Package manager version: (e.g. npm 10.2)
        - Browser: (e.g. Chrome 70.5, if applicable)

  - type: dropdown
    id: urgency
    attributes:
      label: How urgent do you feel this bug is?
      options:
        - P4 (nice to have)
        - P3
        - P2
        - P1
        - P0 (emergency)

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or notes about the problem here, including log output, etc.
